echo: echo.hs
	ghc -dynamic echo.hs -o bin/echo

cat: cat.hs
	ghc -dynamic cat.hs -o bin/cat

touch: touch.hs
	ghc -dynamic touch.hs -o bin/touch

ls: ls.hs
	ghc -dynamic ls.hs -o bin/ls

build: ls touch cat echo
